class MainKiller{
	public static void main(String[] args)
	{
		System.out.println("Running Cylinder in MainKiller");
		Cylinder oxygen=new Cylinder();
		Cylinder fire=new Cylinder();
		Cylinder glass=new Cylinder();
		Cylinder elliptic=new Cylinder();
		Cylinder cylinder=new Cylinder();
		System.out.println("-----------------------");
		System.out.println("invoking Fabric1 in MainKiller");
		Fabric1 nylon=new Fabric1();
		Fabric1 cotton=new Fabric1();
		Fabric1 silk=new Fabric1();
		Fabric1 jeans=new Fabric1();
		Fabric1 wool=new Fabric1();
		System.out.println("-----------------------");
		System.out.println("invoking Vaccum in MainKiller");
		Vaccum clean=new Vaccum();
		Vaccum ref=new Vaccum();
		Vaccum ref1=new Vaccum();
		Vaccum stick=new Vaccum();
		Vaccum robot=new Vaccum();
		System.out.println("-----------------------");
		System.out.println("invoking Engine in MainKiller");
		Engine driver=new Engine();
		Engine petrol=new Engine();
		Engine electric=new Engine();
		Engine diesel=new Engine();
		Engine combustion=new Engine();
		System.out.println("-----------------------");
		System.out.println("invoking ContactLens in MainKiller");
		ContactLens replacement=new ContactLens();
		ContactLens convex=new ContactLens();
		ContactLens concave=new ContactLens();
		ContactLens spectacular=new ContactLens();
		ContactLens rigid=new ContactLens();
		System.out.println("-----------------------");
		System.out.println("invoking Coastal in MainKiller");
		Coastal region=new Coastal();
		Coastal food=new Coastal();
		Coastal entertainment=new Coastal();
		Coastal water=new Coastal();
		Coastal people=new Coastal();
		System.out.println("-----------------------");
		System.out.println("invoking NailCutter in MainKiller");
		NailCutter color=new NailCutter();
		NailCutter use=new NailCutter();
		NailCutter nail=new NailCutter();
		NailCutter ref2=new NailCutter();
		NailCutter cost1=new NailCutter();
		System.out.println("-----------------------");
		System.out.println("invoking Rope in MainKiller");
		Rope lenght=new Rope();
		Rope width=new Rope();
		Rope cost2=new Rope();
		Rope use1=new Rope();
		Rope color1=new Rope();
		System.out.println("-----------------------");
		System.out.println("invoking Wire in MainKiller");
		Wire type=new Wire();
		Wire color2=new Wire();
		Wire price=new Wire();
		Wire electric1=new Wire();
		Wire optical=new Wire();
		System.out.println("-----------------------");
		System.out.println("invoking Tv in MainKiller");
		Tv color3=new Tv();
		Tv blackAndWhite=new Tv();
		Tv cost3=new Tv();
		Tv brand=new Tv();
		Tv purpose=new Tv();
		System.out.println("-----------------------");
		System.out.println("invoking Indicator in MainKiller");
		Indicator price2=new Indicator();
		Indicator ref3=new Indicator();
		Indicator color4=new Indicator();
		Indicator indicator=new Indicator();
		Indicator use3=new Indicator();
		System.out.println("-----------------------");
		System.out.println("invoking NumberPlate in MainKiller");
		NumberPlate number=new NumberPlate();
		NumberPlate vehicle=new NumberPlate();
		NumberPlate state=new NumberPlate();
		NumberPlate ref5=new NumberPlate();
		NumberPlate ref6=new NumberPlate();
		System.out.println("-----------------------");
		System.out.println("invoking Submarine in MainKiller");
		Submarine shape=new Submarine();
		Submarine submarine=new Submarine();
		Submarine type1=new Submarine();
		Submarine robot2=new Submarine();
		Submarine price4=new Submarine();
		System.out.println("-----------------------");
		System.out.println("invoking Robot in MainKiller");
		Robot cost5=new Robot();
		Robot use4=new Robot();
		Robot action=new Robot();
		Robot size=new Robot();
		Robot robot3=new Robot();
		System.out.println("-----------------------");
		System.out.println("invoking MotherBoard in MainKiller");
		MotherBoard memory=new MotherBoard();
		MotherBoard battery=new MotherBoard();
		MotherBoard cpu=new MotherBoard();
		MotherBoard socket=new MotherBoard();
		MotherBoard adapter=new MotherBoard();
		System.out.println("-----------------------");
		System.out.println("invoking Printer in MainKiller");
		Printer brand2=new Printer();
		Printer amount=new Printer();
		Printer color6=new Printer();
		Printer print=new Printer();
		Printer paper=new Printer();
		System.out.println("-----------------------");
		System.out.println("invoking SimCard in MainKiller");
		SimCard prePaid=new SimCard();
		SimCard postPaid=new SimCard();
		SimCard airtel=new SimCard();
		SimCard jio=new SimCard();
		SimCard bsnl=new SimCard();
		System.out.println("-----------------------");
		System.out.println("invoking Train in MainKiller");
		Train numbers=new Train();
		Train route=new Train();
		Train express=new Train();
		Train reservation=new Train();
		Train general=new Train();	
	}
}