package com.xworkz.Polymorphism;

public class MainMethod {
	public static void main(String[] args) {
		System.out.println("Invoking main in MainMethod");
		Bakery bakery = new BakeryInfo();
		bakery.sweet();
		bakery.sweet("Mysore Pak");
		bakery.sweet("Mysore Pak", 25);
		bakery.sweet("Mysore Pak", 25, 1);
		bakery.sweet("Mysore Pak", 25, 1, true);
		bakery.sweet("Mysore Pak", 25, 1, true, "Brown");
		Bakery bakery1 = new Bakery();
		bakery1.sweet();
		bakery1.sweet("Mysore Pak");
		bakery1.sweet("Mysore Pak", 25);
		bakery1.sweet("Mysore Pak", 25, 1);
		bakery1.sweet("Mysore Pak", 25, 1, true);
		bakery1.sweet("Mysore Pak", 25, 1, true, "Yellow");
		System.out.println("******************************************");
		Hotel hotel = new Restaurant();
		hotel.food();
		hotel.food("Dosa");
		hotel.food("Dosa", 100);
		hotel.food("Dosa", 100, 2);
		hotel.food("Dosa", 100, 2, true);
		hotel.food("Dosa", 100, 2, true, "Good");
		Hotel hotel1 = new Hotel();
		hotel1.food();
		hotel1.food("Dosa");
		hotel1.food("Dosa", 100);
		hotel1.food("Dosa", 100, 2);
		hotel1.food("Dosa", 100, 2, true);
		hotel1.food("Dosa", 100, 2, true, "Good");
		System.out.println("******************************************");
		Hospital hospital = new Clinic();
		hospital.treatment();
		hospital.treatment("Narayana Hrudayalaya");
		hospital.treatment("Narayana Hrudayalaya", 50);
		hospital.treatment("Narayana Hrudayalaya", 50, 1000);
		hospital.treatment("Narayana Hrudayalaya", 50, 1000, true);
		hospital.treatment("Narayana Hrudayalaya", 50, 1000, true, "Banglore");
		Hospital hospital1 = new Hospital();
		hospital1.treatment();
		hospital1.treatment("Narayana Hrudayalaya");
		hospital1.treatment("Narayana Hrudayalaya", 50);
		hospital1.treatment("Narayana Hrudayalaya", 50, 1000);
		hospital1.treatment("Narayana Hrudayalaya", 50, 1000, true);
		hospital1.treatment("Narayana Hrudayalaya", 50, 1000, true, "Banglore");
		System.out.println("******************************************");
		Hostel hostel = new Pg();
		hostel.stay();
		hostel.stay("PES girls hostel");
		hostel.stay("PES girls hostel", 56000);
		hostel.stay("PES girls hostel", 56000, 2012);
		hostel.stay("PES girls hostel", 56000, 2012, true);
		hostel.stay("PES girls hostel", 56000, 2012, true, 650);
		Hostel hostel1 = new Hostel();
		hostel1.stay();
		hostel1.stay("PES girls hostel");
		hostel1.stay("PES girls hostel", 56000);
		hostel1.stay("PES girls hostel", 56000, 2012);
		hostel1.stay("PES girls hostel", 56000, 2012, true);
		hostel1.stay("PES girls hostel", 56000, 2012, true, 650);
		System.out.println("******************************************");
		Mall mall = new Dmart();
		mall.shop();
		mall.shop("Mantri square");
		mall.shop("Mantri square", true);
		mall.shop("Mantri square", true, 2001);
		mall.shop("Mantri square", true, 2001, "Banglore");
		mall.shop("Mantri square", true, 2001, "Banglore", true);
		Mall mall1 = new Mall();
		mall1.shop();
		mall1.shop("Mantri square");
		mall1.shop("Mantri square", true);
		mall1.shop("Mantri square", true, 2001);
		mall1.shop("Mantri square", true, 2001, "Banglore");
		mall1.shop("Mantri square", true, 2001, "Banglore", true);
		System.out.println("******************************************");
		Theater theater = new HomeTheater();
		theater.movie();
		theater.movie("Kranthi");
		theater.movie("Kranthi", 2);
		theater.movie("Kranthi", 2, 500);
		theater.movie("Kranthi", 2, 500, 4);
		theater.movie("Kranthi", 2, 500, 4, "banglore");
		Theater theater1 = new Theater();
		theater1.movie();
		theater1.movie("Kranthi");
		theater1.movie("Kranthi", 2);
		theater1.movie("Kranthi", 2, 500);
		theater1.movie("Kranthi", 2, 500, 4);
		theater1.movie("Kranthi", 2, 500, 4, "Banglore");
		System.out.println("******************************************");
		Library library = new DigitalLibrary();
		library.read();
		library.read("Banglore");
		library.read("Banglore", true);
		library.read("Banglore", true, 20);
		library.read("Banglore", true, 20, "Mookajjiya kanasugalu");
		library.read("Banglore", true, 20, "Mookajjiya kanasugalu", 1977);
		Library library1 = new Library();
		library1.read();
		library1.read("Banglore");
		library1.read("Banglore", true);
		library1.read("Banglore", true, 20);
		library1.read("Banglore", true, 20, "Mookajjiya kanasugalu");
		library1.read("Banglore", true, 20, "Mookajjaya kanasugalu", 1977);
		System.out.println("******************************************");
		Temple temple = new Tradition();
		temple.prayer();
		temple.prayer("Shiva");
		temple.prayer("Shiva", 6);
		temple.prayer("Shiva", 6, "Banglore");
		temple.prayer("Shiva", 6, "Banglore", 10);
		temple.prayer("Shiva", 6, "Banglore", 10, true);
		Temple temple1 = new Temple();
		temple1.prayer();
		temple1.prayer("Shiva");
		temple1.prayer("Shiva", 6);
		temple1.prayer("Shiva", 6, "Banglore");
		temple1.prayer("Shiva", 6, "Banglore", 10);
		temple1.prayer("Shiva", 6, "Banglore", 10, true);
		System.out.println("******************************************");
		Market market = new SuperMarket();
		market.sale();
		market.sale("cloth");
		market.sale("cloth", 500);
		market.sale("cloth", 500, "Banglore");
		market.sale("cloth", 500, "Banglore", 1);
		market.sale("cloth", 500, "Banglore", 1, false);
		Market market1 = new Market();
		market1.sale();
		market1.sale("cloth");
		market1.sale("cloth", 500);
		market1.sale("cloth", 500, "Banglore");
		market1.sale("cloth", 500, "Banglore", 1);
		market1.sale("cloth", 500, "Banglore", 1, false);
		System.out.println("******************************************");
		Street street = new Blocks();
		street.area();
		street.area("Rajajinagar");
		street.area("Rajajinagar", 5);
		street.area("Rajajinagar", 5, false);
		street.area("Rajajinagar", 5, false, 6);
		street.area("Rajajinagar", 5, false, 6, true);
		Street street1 = new Street();
		street1.area();
		street1.area("Rajajinagar");
		street1.area("Rajajinagar", 5);
		street1.area("Rajajinagar", 5, false);
		street1.area("Rajajinagar", 5, false, 6);
		street1.area("Rajajinagar", 5, false, 6, true);
		System.out.println("******************************************");
		Zoo zoo = new WildLife();
		zoo.animal();
		zoo.animal("Tiger");
		zoo.animal("Tiger", true);
		zoo.animal("Tiger", true, 5);
		zoo.animal("Tiger", true, 5, true);
		zoo.animal("Tiger", true, 5, true, "White");
		Zoo zoo1 = new Zoo();
		zoo1.animal();
		zoo1.animal("Tiger");
		zoo1.animal("Tiger", true);
		zoo1.animal("Tiger", true, 5);
		zoo1.animal("Tiger", true, 5, true);
		zoo1.animal("Tiger", true, 5, true, "White");
		System.out.println("******************************************");
		City city = new SmartCity();
		city.town();
		city.town("Chikkamagaluru");
		city.town("Chikkamagaluru", true);
		city.town("Chikkamagaluru", true, "coffee");
		city.town("Chikkamagaluru", true, "coffee", true);
		city.town("Chikkamagaluru", true, "coffee", true, 10);
		City city1 = new City();
		city1.town();
		city1.town("Chikkamagaluru");
		city1.town("Chikkamagaluru", true);
		city1.town("Chikkamagaluru", true, "coffee");
		city1.town("Chikkamagaluru", true, "coffee", true);
		city1.town("Chikkamagaluru", true, "coffee", true, 10);
		System.out.println("******************************************");
		Pub pub = new MusicPub();
		pub.enjoy();
		pub.enjoy("Toit BrewPub");
		pub.enjoy("Toit BrewPub", 50);
		pub.enjoy("Toit BrewPub", 50, "Banglore");
		pub.enjoy("Toit BrewPub", 50, "Banglore", 6);
		pub.enjoy("Toit BrewPub", 50, "Banglore", 6, 12);
		Pub pub1 = new Pub();
		pub1.enjoy();
		pub1.enjoy("Toit BrewPub");
		pub1.enjoy("Toit BrewPub", 50);
		pub1.enjoy("Toit BrewPub", 50, "Banglore");
		pub1.enjoy("Toit BrewPub", 50, "Banglore", 6);
		pub1.enjoy("Toit BrewPub", 50, "Banglore", 6, 12);
		System.out.println("******************************************");
		PoliceStation policeStation = new LocalPolice();
		policeStation.protect();
		policeStation.protect("Hebbal police station");
		policeStation.protect("Hebbal police station", 500);
		policeStation.protect("Hebbal police station", 500, "Hebbal");
		policeStation.protect("Hebbal police station", 500, "Hebbal", 15);
		policeStation.protect("Hebbal police station", 500, "Hebbal", 15, true);
		PoliceStation policeStation1 = new PoliceStation();
		policeStation1.protect();
		policeStation1.protect("Hebbal police station");
		policeStation1.protect("Hebbal police station", 500);
		policeStation1.protect("Hebbal police station", 500, "Hebbal");
		policeStation1.protect("Hebbal police station", 500, "Hebbal", 15);
		policeStation1.protect("Hebbal police station", 500, "Hebbal", 15, true);
	}

}
